// src/installations/field-config/autoconsumo.ts
// Perfil AUTOCONSUMO — autoconsumo fotovoltaico.
// potenciaPico: A (obligatorio, kWp). modalidadAutoconsumo: A (obligatorio).
// supplyVoltage default 400.

import { FieldDef } from './field-config';
import {
  TITULAR_FIELDS,
  EMPLAZAMIENTO_DIRECCION_FIELDS,
  EMPLAZAMIENTO_EXTRAS_FIELDS,
  ACOMETIDA_FIELDS,
  CGP_FIELDS,
  LGA_FIELDS,
  MODULO_MEDIDA_FIELDS,
  PROTECCIONES_FIELDS,
  TIERRA_FIELDS,
  EMPRESA_FIELDS,
  INSTALADOR_FIELDS,
  DISTRIBUIDORA_FIELD,
  PRESUPUESTO_FIELDS,
  CERTIFICACION_FIELDS,
  FIRMA_FIELDS,
  INFO_FIELDS,
} from './shared-fields';

const TECNICO_FIELDS: FieldDef[] = [
  {
    name: 'tipoDocumentacion',
    group: 'C',
    section: 'tecnico',
    label: 'Tipo documentacion',
    calculatedBy: 'auto: MTD si P <= 100kW (ITC-BT-04 grupo o)',
    requiredForDocs: ['CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'supplyVoltage',
    group: 'B',
    section: 'tecnico',
    label: 'Tension (V)',
    defaultValue: 400,
    inputType: 'select',
    options: ['230', '400'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'tipoActuacion',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo actuacion',
    defaultValue: 'Nueva',
    inputType: 'select',
    options: ['Nueva', 'Ampliacion con o sin modif.', 'Modificacion'],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'usoInstalacion',
    group: 'B',
    section: 'tecnico',
    label: 'Uso instalacion',
    defaultValue: 'Autoconsumo',
    inputType: 'text',
    requiredForDocs: ['MTD', 'SOLICITUD_BT'],
  },
  {
    name: 'tipoInstalacionCie',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo instalacion CIE',
    defaultValue: 'Autoconsumo',
    inputType: 'select',
    options: [
      'Autoconsumo',
      'Local comercial',
      'Oficina',
      'Vivienda',
      'Nave industrial',
      'Garaje',
      'Alumbrado exterior',
      'IRVE',
      'Piscina',
      'Local de publica concurrencia',
      'Instalacion temporal',
    ],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'potenciaPico',
    group: 'A',
    section: 'tecnico',
    label: 'Potencia pico (kWp)',
    inputType: 'number',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'modalidadAutoconsumo',
    group: 'A',
    section: 'tecnico',
    label: 'Modalidad autoconsumo',
    inputType: 'select',
    options: ['sin_excedentes', 'con_excedentes_acogida', 'con_excedentes_no_acogida'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'installationType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo instalacion (wizard)',
    defaultValue: 'autoconsumo',
    inputType: 'text',
  },
  {
    name: 'expedienteType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo expediente',
    defaultValue: 'NUEVA',
    inputType: 'text',
  },
  {
    name: 'referencia',
    group: 'A',
    section: 'tecnico',
    label: 'Referencia interna',
    inputType: 'text',
    optional: true,
  },
  {
    name: 'esquemaDistribucion',
    group: 'B',
    section: 'tecnico',
    label: 'Esquema distribucion',
    defaultValue: 'TT',
    inputType: 'select',
    options: ['TT', 'TN-S', 'TN-C', 'TN-C-S', 'IT'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  // gradoElectrificacion: grupo D (no aplica)
  {
    name: 'seccionDi',
    group: 'B',
    section: 'tecnico',
    label: 'Seccion DI (mm2)',
    defaultValue: 10,
    inputType: 'number',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'potMaxAdmisible',
    group: 'C',
    section: 'tecnico',
    label: 'Potencia maxima admisible (kW)',
    calculatedBy: 'formula: V x IGA',
    requiredForDocs: ['CIE'],
  },
];

export const AUTOCONSUMO_FIELDS: FieldDef[] = [
  ...TITULAR_FIELDS,
  ...EMPLAZAMIENTO_DIRECCION_FIELDS,
  ...EMPLAZAMIENTO_EXTRAS_FIELDS,
  ...TECNICO_FIELDS,
  ...DISTRIBUIDORA_FIELD,
  ...ACOMETIDA_FIELDS,
  ...CGP_FIELDS,
  ...LGA_FIELDS,
  ...MODULO_MEDIDA_FIELDS,
  ...PROTECCIONES_FIELDS,
  ...TIERRA_FIELDS,
  ...EMPRESA_FIELDS,
  ...INSTALADOR_FIELDS,
  ...PRESUPUESTO_FIELDS,
  ...CERTIFICACION_FIELDS,
  ...FIRMA_FIELDS,
  ...INFO_FIELDS,
];
