// src/installations/field-config/enlace.ts
// Perfil ENLACE — instalaciones de enlace y comunes de edificio.
// LGA: A (obligatorio). CGP: A (obligatorio). supplyVoltage default 400 trifasico.
// Nota: numViviendas, numLocales no existen en schema.prisma — se omiten.

import { FieldDef } from './field-config';
import {
  TITULAR_FIELDS,
  EMPLAZAMIENTO_DIRECCION_FIELDS,
  EMPLAZAMIENTO_EXTRAS_FIELDS,
  LGA_FIELDS,
  MODULO_MEDIDA_FIELDS,
  PROTECCIONES_FIELDS,
  TIERRA_FIELDS,
  EMPRESA_FIELDS,
  INSTALADOR_FIELDS,
  DISTRIBUIDORA_FIELD,
  PRESUPUESTO_FIELDS,
  CERTIFICACION_FIELDS,
  FIRMA_FIELDS,
  INFO_FIELDS,
} from './shared-fields';

// Acometida obligatoria para enlace
const ACOMETIDA_ENLACE: FieldDef[] = [
  {
    name: 'puntoConexion',
    group: 'A',
    section: 'acometida',
    label: 'Punto de conexion',
    inputType: 'select',
    options: ['RBT', 'CT', 'IA'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'tipoAcometida',
    group: 'A',
    section: 'acometida',
    label: 'Tipo acometida',
    inputType: 'select',
    options: ['AEREA', 'SUBTERRANEA'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'seccionAcometida',
    group: 'C',
    section: 'acometida',
    label: 'Seccion acometida (mm2)',
    calculatedBy: 'motor',
    requiredForDocs: ['MTD'],
  },
  {
    name: 'materialAcometida',
    group: 'A',
    section: 'acometida',
    label: 'Material acometida',
    inputType: 'select',
    options: ['CU', 'AL'],
    requiredForDocs: ['MTD'],
  },
];

// CGP obligatorio para enlace
const CGP_ENLACE: FieldDef[] = [
  {
    name: 'tipoCgp',
    group: 'A',
    section: 'cgp',
    label: 'Tipo CGP',
    inputType: 'select',
    options: ['CGP', 'BTV', 'N/A'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'esquemaCgp',
    group: 'A',
    section: 'cgp',
    label: 'Esquema CGP',
    inputType: 'select',
    options: ['7', '8', '9', '10', '11'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'inBaseCgp',
    group: 'C',
    section: 'cgp',
    label: 'Corriente base fusible (A)',
    calculatedBy: 'motor: desde potencia',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'inCartuchoCgp',
    group: 'C',
    section: 'cgp',
    label: 'Corriente cartucho fusible (A)',
    calculatedBy: 'motor: desde potencia',
    requiredForDocs: ['MTD'],
  },
];

const TECNICO_FIELDS: FieldDef[] = [
  {
    name: 'tipoDocumentacion',
    group: 'C',
    section: 'tecnico',
    label: 'Tipo documentacion',
    calculatedBy: 'auto: MTD salvo P > 100kW (ITC-BT-04 grupo e)',
    requiredForDocs: ['CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'supplyVoltage',
    group: 'B',
    section: 'tecnico',
    label: 'Tension (V)',
    defaultValue: 400,
    inputType: 'select',
    options: ['230', '400'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'tipoActuacion',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo actuacion',
    defaultValue: 'Nueva',
    inputType: 'select',
    options: ['Nueva', 'Ampliacion con o sin modif.', 'Modificacion'],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'usoInstalacion',
    group: 'B',
    section: 'tecnico',
    label: 'Uso instalacion',
    defaultValue: 'Enlace y comunes',
    inputType: 'text',
    requiredForDocs: ['MTD', 'SOLICITUD_BT'],
  },
  {
    name: 'tipoInstalacionCie',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo instalacion CIE',
    defaultValue: 'Vivienda',
    inputType: 'select',
    options: [
      'Vivienda',
      'Local comercial',
      'Oficina',
      'Nave industrial',
      'Garaje',
      'Alumbrado exterior',
      'IRVE',
      'Autoconsumo',
      'Piscina',
      'Local de publica concurrencia',
      'Instalacion temporal',
    ],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'installationType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo instalacion (wizard)',
    defaultValue: 'enlace',
    inputType: 'text',
  },
  {
    name: 'expedienteType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo expediente',
    defaultValue: 'NUEVA',
    inputType: 'text',
  },
  {
    name: 'referencia',
    group: 'A',
    section: 'tecnico',
    label: 'Referencia interna',
    inputType: 'text',
    optional: true,
  },
  {
    name: 'esquemaDistribucion',
    group: 'B',
    section: 'tecnico',
    label: 'Esquema distribucion',
    defaultValue: 'TT',
    inputType: 'select',
    options: ['TT', 'TN-S', 'TN-C', 'TN-C-S', 'IT'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  // gradoElectrificacion: grupo D (no aplica para enlace)
  {
    name: 'seccionDi',
    group: 'B',
    section: 'tecnico',
    label: 'Seccion DI (mm2)',
    defaultValue: 10,
    inputType: 'number',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'potMaxAdmisible',
    group: 'C',
    section: 'tecnico',
    label: 'Potencia maxima admisible (kW)',
    calculatedBy: 'formula: V x IGA',
    requiredForDocs: ['CIE'],
  },
];

export const ENLACE_FIELDS: FieldDef[] = [
  ...TITULAR_FIELDS,
  ...EMPLAZAMIENTO_DIRECCION_FIELDS,
  ...EMPLAZAMIENTO_EXTRAS_FIELDS,
  ...TECNICO_FIELDS,
  ...DISTRIBUIDORA_FIELD,
  ...ACOMETIDA_ENLACE,
  ...CGP_ENLACE,
  ...LGA_FIELDS,
  ...MODULO_MEDIDA_FIELDS,
  ...PROTECCIONES_FIELDS,
  ...TIERRA_FIELDS,
  ...EMPRESA_FIELDS,
  ...INSTALADOR_FIELDS,
  ...PRESUPUESTO_FIELDS,
  ...CERTIFICACION_FIELDS,
  ...FIRMA_FIELDS,
  ...INFO_FIELDS,
];
