// src/installations/field-config/industrial.ts
// Perfil INDUSTRIAL — nave industrial, taller.
// gradoElectrificacion: D (no aplica). Superficie: A (min 125W/m2).
// supplyVoltage default 400 trifasico. Acometida: A (obligatorio).

import { FieldDef } from './field-config';
import {
  TITULAR_FIELDS,
  EMPLAZAMIENTO_DIRECCION_FIELDS,
  EMPLAZAMIENTO_EXTRAS_FIELDS,
  CGP_FIELDS,
  LGA_FIELDS,
  MODULO_MEDIDA_FIELDS,
  PROTECCIONES_FIELDS,
  TIERRA_FIELDS,
  EMPRESA_FIELDS,
  INSTALADOR_FIELDS,
  DISTRIBUIDORA_FIELD,
  PRESUPUESTO_FIELDS,
  CERTIFICACION_FIELDS,
  FIRMA_FIELDS,
  INFO_FIELDS,
  replaceField,
} from './shared-fields';

// Acometida con campos A (obligatorio para industrial)
const ACOMETIDA_INDUSTRIAL: FieldDef[] = [
  {
    name: 'puntoConexion',
    group: 'A',
    section: 'acometida',
    label: 'Punto de conexion',
    inputType: 'select',
    options: ['RBT', 'CT', 'IA'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'tipoAcometida',
    group: 'A',
    section: 'acometida',
    label: 'Tipo acometida',
    inputType: 'select',
    options: ['AEREA', 'SUBTERRANEA'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'seccionAcometida',
    group: 'C',
    section: 'acometida',
    label: 'Seccion acometida (mm2)',
    calculatedBy: 'motor',
    requiredForDocs: ['MTD'],
  },
  {
    name: 'materialAcometida',
    group: 'A',
    section: 'acometida',
    label: 'Material acometida',
    inputType: 'select',
    options: ['CU', 'AL'],
    requiredForDocs: ['MTD'],
  },
];

const TECNICO_FIELDS: FieldDef[] = [
  {
    name: 'tipoDocumentacion',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo documentacion',
    defaultValue: 'MTD',
    inputType: 'text',
    requiredForDocs: ['CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'supplyType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo suministro',
    defaultValue: 'LOCAL_COMERCIAL',
    inputType: 'select',
    options: ['LOCAL_COMERCIAL', 'VIVIENDA_BASICA', 'VIVIENDA_ELEVADA'],
    requiredForDocs: ['MTD'],
  },
  {
    name: 'supplyVoltage',
    group: 'B',
    section: 'tecnico',
    label: 'Tension (V)',
    defaultValue: 400,
    inputType: 'select',
    options: ['230', '400'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'tipoActuacion',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo actuacion',
    defaultValue: 'Nueva',
    inputType: 'select',
    options: ['Nueva', 'Ampliacion con o sin modif.', 'Modificacion'],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'usoInstalacion',
    group: 'B',
    section: 'tecnico',
    label: 'Uso instalacion',
    defaultValue: 'Industrial',
    inputType: 'text',
    requiredForDocs: ['MTD', 'SOLICITUD_BT'],
  },
  {
    name: 'tipoInstalacionCie',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo instalacion CIE',
    defaultValue: 'Nave industrial',
    inputType: 'select',
    options: [
      'Nave industrial',
      'Local comercial',
      'Oficina',
      'Vivienda',
      'Garaje',
      'Alumbrado exterior',
      'IRVE',
      'Autoconsumo',
      'Piscina',
      'Local de publica concurrencia',
      'Instalacion temporal',
    ],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'installationType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo instalacion (wizard)',
    defaultValue: 'industrial',
    inputType: 'text',
  },
  {
    name: 'expedienteType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo expediente',
    defaultValue: 'NUEVA',
    inputType: 'text',
  },
  {
    name: 'referencia',
    group: 'A',
    section: 'tecnico',
    label: 'Referencia interna',
    inputType: 'text',
    optional: true,
  },
  {
    name: 'esquemaDistribucion',
    group: 'B',
    section: 'tecnico',
    label: 'Esquema distribucion',
    defaultValue: 'TT',
    inputType: 'select',
    options: ['TT', 'TN-S', 'TN-C', 'TN-C-S', 'IT'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  // gradoElectrificacion: grupo D (no aplica para industrial)
  {
    name: 'seccionDi',
    group: 'B',
    section: 'tecnico',
    label: 'Seccion DI (mm2)',
    defaultValue: 10,
    inputType: 'number',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'potMaxAdmisible',
    group: 'C',
    section: 'tecnico',
    label: 'Potencia maxima admisible (kW)',
    calculatedBy: 'formula: V x IGA',
    requiredForDocs: ['CIE'],
  },
];

export const INDUSTRIAL_FIELDS: FieldDef[] = [
  ...TITULAR_FIELDS,
  ...EMPLAZAMIENTO_DIRECCION_FIELDS,
  ...EMPLAZAMIENTO_EXTRAS_FIELDS,
  ...TECNICO_FIELDS,
  ...DISTRIBUIDORA_FIELD,
  ...ACOMETIDA_INDUSTRIAL,
  ...CGP_FIELDS,
  ...LGA_FIELDS,
  ...MODULO_MEDIDA_FIELDS,
  ...PROTECCIONES_FIELDS,
  ...TIERRA_FIELDS,
  ...EMPRESA_FIELDS,
  ...INSTALADOR_FIELDS,
  ...PRESUPUESTO_FIELDS,
  ...CERTIFICACION_FIELDS,
  ...FIRMA_FIELDS,
  ...INFO_FIELDS,
];
