// src/installations/field-config/temporal.ts
// Perfil TEMPORAL — instalacion temporal (obras, ferias).
// gradoElectrificacion: D. temporalidad: A (obligatorio, num dias).
// Simplificado: no pide puesta a tierra completa.

import { FieldDef } from './field-config';
import {
  TITULAR_FIELDS,
  EMPLAZAMIENTO_DIRECCION_FIELDS,
  EMPLAZAMIENTO_EXTRAS_FIELDS,
  ACOMETIDA_FIELDS,
  CGP_FIELDS,
  MODULO_MEDIDA_FIELDS,
  PROTECCIONES_FIELDS,
  EMPRESA_FIELDS,
  INSTALADOR_FIELDS,
  DISTRIBUIDORA_FIELD,
  PRESUPUESTO_FIELDS,
  CERTIFICACION_FIELDS,
  FIRMA_FIELDS,
  INFO_FIELDS,
} from './shared-fields';

// Tierra simplificada para temporal (solo resistencia + aislamiento)
const TIERRA_TEMPORAL: FieldDef[] = [
  {
    name: 'tipoElectrodos',
    group: 'B',
    section: 'tierra',
    label: 'Tipo electrodos',
    defaultValue: 'PICAS',
    inputType: 'select',
    options: ['PICAS', 'PLACAS', 'MALLAS'],
    requiredForDocs: ['MTD'],
  },
  {
    name: 'resistenciaTierra',
    group: 'A',
    section: 'tierra',
    label: 'Resistencia tierra (ohm)',
    inputType: 'number',
    requiredForDocs: ['CIE'],
  },
  {
    name: 'resistenciaAislamiento',
    group: 'A',
    section: 'tierra',
    label: 'Resistencia aislamiento (Mohm)',
    inputType: 'number',
    requiredForDocs: ['CIE'],
  },
];

const TECNICO_FIELDS: FieldDef[] = [
  {
    name: 'tipoDocumentacion',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo documentacion',
    defaultValue: 'MTD',
    inputType: 'text',
    requiredForDocs: ['CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'supplyVoltage',
    group: 'B',
    section: 'tecnico',
    label: 'Tension (V)',
    defaultValue: 230,
    inputType: 'select',
    options: ['230', '400'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'tipoActuacion',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo actuacion',
    defaultValue: 'Nueva',
    inputType: 'select',
    options: ['Nueva'],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'usoInstalacion',
    group: 'B',
    section: 'tecnico',
    label: 'Uso instalacion',
    defaultValue: 'Instalacion temporal',
    inputType: 'text',
    requiredForDocs: ['MTD', 'SOLICITUD_BT'],
  },
  {
    name: 'tipoInstalacionCie',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo instalacion CIE',
    defaultValue: 'Instalacion temporal',
    inputType: 'select',
    options: [
      'Instalacion temporal',
      'Local comercial',
      'Oficina',
      'Vivienda',
      'Nave industrial',
      'Garaje',
      'Alumbrado exterior',
      'IRVE',
      'Autoconsumo',
      'Piscina',
      'Local de publica concurrencia',
    ],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'temporalidad',
    group: 'A',
    section: 'tecnico',
    label: 'Temporalidad (dias)',
    inputType: 'number',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'installationType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo instalacion (wizard)',
    defaultValue: 'temporal',
    inputType: 'text',
  },
  {
    name: 'expedienteType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo expediente',
    defaultValue: 'NUEVA',
    inputType: 'text',
  },
  {
    name: 'referencia',
    group: 'A',
    section: 'tecnico',
    label: 'Referencia interna',
    inputType: 'text',
    optional: true,
  },
  {
    name: 'esquemaDistribucion',
    group: 'B',
    section: 'tecnico',
    label: 'Esquema distribucion',
    defaultValue: 'TT',
    inputType: 'select',
    options: ['TT', 'TN-S', 'TN-C', 'TN-C-S', 'IT'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  // gradoElectrificacion: grupo D (no aplica)
  {
    name: 'seccionDi',
    group: 'B',
    section: 'tecnico',
    label: 'Seccion DI (mm2)',
    defaultValue: 6,
    inputType: 'number',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'potMaxAdmisible',
    group: 'C',
    section: 'tecnico',
    label: 'Potencia maxima admisible (kW)',
    calculatedBy: 'formula: V x IGA',
    requiredForDocs: ['CIE'],
  },
];

export const TEMPORAL_FIELDS: FieldDef[] = [
  ...TITULAR_FIELDS,
  ...EMPLAZAMIENTO_DIRECCION_FIELDS,
  ...EMPLAZAMIENTO_EXTRAS_FIELDS,
  ...TECNICO_FIELDS,
  ...DISTRIBUIDORA_FIELD,
  ...ACOMETIDA_FIELDS,
  ...CGP_FIELDS,
  // LGA: no aplica para temporal
  ...MODULO_MEDIDA_FIELDS,
  ...PROTECCIONES_FIELDS,
  ...TIERRA_TEMPORAL,
  ...EMPRESA_FIELDS,
  ...INSTALADOR_FIELDS,
  ...PRESUPUESTO_FIELDS,
  ...CERTIFICACION_FIELDS,
  ...FIRMA_FIELDS,
  ...INFO_FIELDS,
];
