// src/installations/field-config/vivienda-ampliacion.ts
// Perfil VIVIENDA_AMPLIACION — vivienda ampliacion/modificacion.
// Igual que vivienda nueva + numRegistroExistente, potOriginal, potAmpliacion.

import { FieldDef } from './field-config';
import {
  TITULAR_FIELDS,
  EMPLAZAMIENTO_DIRECCION_FIELDS,
  EMPLAZAMIENTO_EXTRAS_FIELDS,
  ACOMETIDA_FIELDS,
  CGP_FIELDS,
  LGA_FIELDS,
  MODULO_MEDIDA_FIELDS,
  PROTECCIONES_FIELDS,
  TIERRA_FIELDS,
  EMPRESA_FIELDS,
  INSTALADOR_FIELDS,
  DISTRIBUIDORA_FIELD,
  PRESUPUESTO_FIELDS,
  CERTIFICACION_FIELDS,
  FIRMA_FIELDS,
  INFO_FIELDS,
} from './shared-fields';

const TECNICO_FIELDS: FieldDef[] = [
  {
    name: 'tipoDocumentacion',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo documentacion',
    defaultValue: 'MTD',
    inputType: 'text',
    requiredForDocs: ['CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'supplyType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo suministro',
    defaultValue: 'VIVIENDA_BASICA',
    inputType: 'select',
    options: ['VIVIENDA_BASICA', 'VIVIENDA_ELEVADA'],
    requiredForDocs: ['MTD'],
  },
  {
    name: 'supplyVoltage',
    group: 'B',
    section: 'tecnico',
    label: 'Tension (V)',
    defaultValue: 230,
    inputType: 'select',
    options: ['230', '400'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'tipoActuacion',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo actuacion',
    defaultValue: 'Ampliacion con o sin modif.',
    inputType: 'select',
    options: ['Ampliacion con o sin modif.', 'Modificacion'],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'usoInstalacion',
    group: 'B',
    section: 'tecnico',
    label: 'Uso instalacion',
    defaultValue: 'Vivienda',
    inputType: 'text',
    requiredForDocs: ['MTD', 'SOLICITUD_BT'],
  },
  {
    name: 'tipoInstalacionCie',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo instalacion CIE',
    defaultValue: 'Vivienda',
    inputType: 'select',
    options: [
      'Vivienda',
      'Local comercial',
      'Oficina',
      'Nave industrial',
      'Garaje',
      'Alumbrado exterior',
      'IRVE',
      'Autoconsumo',
      'Piscina',
      'Local de publica concurrencia',
      'Instalacion temporal',
    ],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'aforo',
    group: 'B',
    section: 'tecnico',
    label: 'Aforo',
    defaultValue: 'N/A',
    inputType: 'text',
    requiredForDocs: ['CIE'],
  },
  {
    name: 'installationType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo instalacion (wizard)',
    defaultValue: 'vivienda',
    inputType: 'text',
  },
  {
    name: 'expedienteType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo expediente',
    defaultValue: 'AMPLIACION',
    inputType: 'text',
  },
  {
    name: 'numRegistroExistente',
    group: 'A',
    section: 'tecnico',
    label: 'Num. registro instalacion existente',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'potOriginal',
    group: 'A',
    section: 'tecnico',
    label: 'Potencia original (W)',
    inputType: 'number',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'potAmpliacion',
    group: 'A',
    section: 'tecnico',
    label: 'Potencia ampliacion (W)',
    inputType: 'number',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'referencia',
    group: 'A',
    section: 'tecnico',
    label: 'Referencia interna',
    inputType: 'text',
    optional: true,
  },
  {
    name: 'esquemaDistribucion',
    group: 'B',
    section: 'tecnico',
    label: 'Esquema distribucion',
    defaultValue: 'TT',
    inputType: 'select',
    options: ['TT', 'TN-S', 'TN-C', 'TN-C-S', 'IT'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'gradoElectrificacion',
    group: 'C',
    section: 'tecnico',
    label: 'Grado electrificacion',
    calculatedBy: 'motor: superficie + cargas',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'seccionDi',
    group: 'B',
    section: 'tecnico',
    label: 'Seccion DI (mm2)',
    defaultValue: 6,
    inputType: 'number',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'potMaxAdmisible',
    group: 'C',
    section: 'tecnico',
    label: 'Potencia maxima admisible (kW)',
    calculatedBy: 'formula: V x IGA',
    requiredForDocs: ['CIE'],
  },
];

export const VIVIENDA_AMPLIACION_FIELDS: FieldDef[] = [
  ...TITULAR_FIELDS,
  ...EMPLAZAMIENTO_DIRECCION_FIELDS,
  ...EMPLAZAMIENTO_EXTRAS_FIELDS,
  ...TECNICO_FIELDS,
  ...DISTRIBUIDORA_FIELD,
  ...ACOMETIDA_FIELDS,
  ...CGP_FIELDS,
  ...LGA_FIELDS,
  ...MODULO_MEDIDA_FIELDS,
  ...PROTECCIONES_FIELDS,
  ...TIERRA_FIELDS,
  ...EMPRESA_FIELDS,
  ...INSTALADOR_FIELDS,
  ...PRESUPUESTO_FIELDS,
  ...CERTIFICACION_FIELDS,
  ...FIRMA_FIELDS,
  ...INFO_FIELDS,
];
