// src/installations/field-config/vivienda-nueva.ts
// Configuracion completa de campos para perfil VIVIENDA_NUEVA (CAM).
// Basado en docs/H7_CAMPOS_VIVIENDA_NUEVA.md — TAREA 5.
// Los campos de grupo D (no aplican) NO se incluyen en el array.

import { FieldDef } from './field-config';

export const VIVIENDA_NUEVA_FIELDS: FieldDef[] = [
  // ═══ TITULAR ═══
  {
    name: 'holderDocType',
    group: 'B',
    section: 'titular',
    label: 'Tipo documento',
    defaultValue: 'NIF',
    inputType: 'select',
    options: ['NIF', 'NIE', 'CIF', 'PASAPORTE'],
  },
  {
    name: 'titularNif',
    group: 'A',
    section: 'titular',
    label: 'NIF/NIE/CIF',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularNombre',
    group: 'A',
    section: 'titular',
    label: 'Nombre',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularApellido1',
    group: 'A',
    section: 'titular',
    label: 'Primer apellido',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularApellido2',
    group: 'A',
    section: 'titular',
    label: 'Segundo apellido',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularTipoVia',
    group: 'A',
    section: 'titular',
    label: 'Tipo via',
    inputType: 'select',
    options: ['CALLE', 'AVENIDA', 'PLAZA', 'PASEO', 'CAMINO', 'CARRETERA', 'TRAVESIA', 'RONDA', 'GLORIETA', 'URBANIZACION', 'BULEVAR', 'GRAN VIA', 'PASAJE'],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularNombreVia',
    group: 'A',
    section: 'titular',
    label: 'Nombre via',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularNumero',
    group: 'A',
    section: 'titular',
    label: 'Numero',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularBloque',
    group: 'A',
    section: 'titular',
    label: 'Bloque',
    inputType: 'text',
    optional: true,
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularEscalera',
    group: 'A',
    section: 'titular',
    label: 'Escalera',
    inputType: 'text',
    optional: true,
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularPiso',
    group: 'A',
    section: 'titular',
    label: 'Piso',
    inputType: 'text',
    optional: true,
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularPuerta',
    group: 'A',
    section: 'titular',
    label: 'Puerta',
    inputType: 'text',
    optional: true,
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularLocalidad',
    group: 'A',
    section: 'titular',
    label: 'Municipio',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularProvincia',
    group: 'B',
    section: 'titular',
    label: 'Provincia',
    defaultValue: 'MADRID',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularCp',
    group: 'A',
    section: 'titular',
    label: 'Codigo postal',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularEmail',
    group: 'A',
    section: 'titular',
    label: 'Email',
    inputType: 'text',
    requiredForDocs: ['CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularTelefono',
    group: 'A',
    section: 'titular',
    label: 'Telefono fijo',
    inputType: 'text',
    atLeastOneOf: 'titular_phone',
    requiredForDocs: ['CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'titularMovil',
    group: 'A',
    section: 'titular',
    label: 'Telefono movil',
    inputType: 'text',
    atLeastOneOf: 'titular_phone',
    requiredForDocs: ['CIE', 'SOLICITUD_BT'],
  },
  // representanteNombre, representanteNif → grupo D (no aplica en vivienda persona fisica)

  // ═══ EMPLAZAMIENTO ═══
  {
    name: 'emplazTipoVia',
    group: 'A',
    section: 'emplazamiento',
    label: 'Tipo via',
    inputType: 'select',
    options: ['CALLE', 'AVENIDA', 'PLAZA', 'PASEO', 'CAMINO', 'CARRETERA', 'TRAVESIA', 'RONDA', 'GLORIETA', 'URBANIZACION', 'BULEVAR', 'GRAN VIA', 'PASAJE'],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'emplazNombreVia',
    group: 'A',
    section: 'emplazamiento',
    label: 'Nombre via',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'emplazNumero',
    group: 'A',
    section: 'emplazamiento',
    label: 'Numero',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'emplazBloque',
    group: 'A',
    section: 'emplazamiento',
    label: 'Bloque',
    inputType: 'text',
    optional: true,
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'emplazEscalera',
    group: 'A',
    section: 'emplazamiento',
    label: 'Escalera',
    inputType: 'text',
    optional: true,
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'emplazPiso',
    group: 'A',
    section: 'emplazamiento',
    label: 'Piso',
    inputType: 'text',
    optional: true,
    requiredForDocs: ['MTD'],
  },
  {
    name: 'emplazPuerta',
    group: 'A',
    section: 'emplazamiento',
    label: 'Puerta',
    inputType: 'text',
    optional: true,
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'emplazLocalidad',
    group: 'A',
    section: 'emplazamiento',
    label: 'Municipio',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'emplazProvincia',
    group: 'B',
    section: 'emplazamiento',
    label: 'Provincia',
    defaultValue: 'MADRID',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'emplazCp',
    group: 'A',
    section: 'emplazamiento',
    label: 'Codigo postal',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'superficieM2',
    group: 'A',
    section: 'emplazamiento',
    label: 'Superficie (m2)',
    inputType: 'number',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'cups',
    group: 'A',
    section: 'emplazamiento',
    label: 'CUPS',
    inputType: 'text',
    optional: true,
    requiredForDocs: ['CIE'],
  },
  {
    name: 'contadorUbicacion',
    group: 'B',
    section: 'emplazamiento',
    label: 'Ubicacion contador',
    defaultValue: 'CPM',
    inputType: 'select',
    options: ['ARMARIO', 'LOCAL', 'CPM'],
    requiredForDocs: ['MTD', 'CIE'],
  },

  // ═══ DATOS TECNICOS ═══
  {
    name: 'tipoDocumentacion',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo documentacion',
    defaultValue: 'MTD',
    inputType: 'text',
    requiredForDocs: ['CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'supplyType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo suministro',
    defaultValue: 'VIVIENDA_BASICA',
    inputType: 'select',
    options: ['VIVIENDA_BASICA', 'VIVIENDA_ELEVADA'],
    requiredForDocs: ['MTD'],
  },
  {
    name: 'supplyVoltage',
    group: 'B',
    section: 'tecnico',
    label: 'Tension (V)',
    defaultValue: 230,
    inputType: 'select',
    options: ['230', '400'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'tipoActuacion',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo actuacion',
    defaultValue: 'Nueva',
    inputType: 'select',
    options: ['Nueva', 'Ampliacion con o sin modif.', 'Modificacion'],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'usoInstalacion',
    group: 'B',
    section: 'tecnico',
    label: 'Uso instalacion',
    defaultValue: 'Vivienda',
    inputType: 'text',
    requiredForDocs: ['MTD', 'SOLICITUD_BT'],
  },
  {
    name: 'tipoInstalacionCie',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo instalacion CIE',
    defaultValue: 'Vivienda',
    inputType: 'select',
    options: [
      'Vivienda',
      'Local comercial',
      'Oficina',
      'Nave industrial',
      'Garaje',
      'Alumbrado exterior',
      'IRVE',
      'Autoconsumo',
      'Piscina',
      'Local de publica concurrencia',
      'Instalacion temporal',
    ],
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'aforo',
    group: 'B',
    section: 'tecnico',
    label: 'Aforo',
    defaultValue: 'N/A',
    inputType: 'text',
    requiredForDocs: ['CIE'],
  },
  {
    name: 'installationType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo instalacion (wizard)',
    defaultValue: 'vivienda',
    inputType: 'text',
  },
  {
    name: 'expedienteType',
    group: 'B',
    section: 'tecnico',
    label: 'Tipo expediente',
    defaultValue: 'NUEVA',
    inputType: 'text',
  },
  {
    name: 'referencia',
    group: 'A',
    section: 'tecnico',
    label: 'Referencia interna',
    inputType: 'text',
    optional: true,
  },
  {
    name: 'esquemaDistribucion',
    group: 'B',
    section: 'tecnico',
    label: 'Esquema distribucion',
    defaultValue: 'TT',
    inputType: 'select',
    options: ['TT', 'TN-S', 'TN-C', 'TN-C-S', 'IT'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  // gradoElectrificacion → grupo C (calculado)
  {
    name: 'gradoElectrificacion',
    group: 'C',
    section: 'tecnico',
    label: 'Grado electrificacion',
    calculatedBy: 'motor: superficie + cargas',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'seccionDi',
    group: 'B',
    section: 'tecnico',
    label: 'Seccion DI (mm2)',
    defaultValue: 6,
    inputType: 'number',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'potMaxAdmisible',
    group: 'C',
    section: 'tecnico',
    label: 'Potencia maxima admisible (kW)',
    calculatedBy: 'formula: V x IGA',
    requiredForDocs: ['CIE'],
  },
  // temporalidad, numRegistroExistente, potAmpliacion, potOriginal → grupo D (no aplica)
  // contractedPower → grupo D (legacy)

  // ═══ ACOMETIDA ═══
  {
    name: 'puntoConexion',
    group: 'B',
    section: 'acometida',
    label: 'Punto de conexion',
    defaultValue: 'RBT',
    inputType: 'select',
    options: ['RBT', 'CT', 'IA'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'tipoAcometida',
    group: 'B',
    section: 'acometida',
    label: 'Tipo acometida',
    defaultValue: 'SUBTERRANEA',
    inputType: 'select',
    options: ['AEREA', 'SUBTERRANEA'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'seccionAcometida',
    group: 'C',
    section: 'acometida',
    label: 'Seccion acometida (mm2)',
    calculatedBy: 'motor',
    requiredForDocs: ['MTD'],
  },
  {
    name: 'materialAcometida',
    group: 'B',
    section: 'acometida',
    label: 'Material acometida',
    defaultValue: 'CU',
    inputType: 'select',
    options: ['CU', 'AL'],
    requiredForDocs: ['MTD'],
  },

  // ═══ CGP ═══
  {
    name: 'tipoCgp',
    group: 'B',
    section: 'cgp',
    label: 'Tipo CGP',
    defaultValue: 'CGP',
    inputType: 'select',
    options: ['CGP', 'BTV', 'N/A'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'esquemaCgp',
    group: 'B',
    section: 'cgp',
    label: 'Esquema CGP',
    defaultValue: '7',
    inputType: 'select',
    options: ['7', '8', '9', '10', '11'],
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'inBaseCgp',
    group: 'C',
    section: 'cgp',
    label: 'Corriente base fusible (A)',
    calculatedBy: 'motor: desde potencia',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'inCartuchoCgp',
    group: 'C',
    section: 'cgp',
    label: 'Corriente cartucho fusible (A)',
    calculatedBy: 'motor: desde potencia',
    requiredForDocs: ['MTD'],
  },

  // ═══ LGA ═══
  {
    name: 'seccionLga',
    group: 'C',
    section: 'lga',
    label: 'Seccion LGA (mm2)',
    calculatedBy: 'motor',
    requiredForDocs: ['MTD'],
  },
  {
    name: 'materialLga',
    group: 'B',
    section: 'lga',
    label: 'Material LGA',
    defaultValue: 'CU',
    inputType: 'select',
    options: ['CU', 'AL'],
    requiredForDocs: ['MTD'],
  },
  {
    name: 'longitudLga',
    group: 'C',
    section: 'lga',
    label: 'Longitud LGA (m)',
    calculatedBy: 'motor',
    requiredForDocs: ['MTD'],
  },
  {
    name: 'aislamientoLga',
    group: 'C',
    section: 'lga',
    label: 'Aislamiento LGA',
    calculatedBy: 'motor',
    requiredForDocs: ['MTD'],
  },

  // ═══ MODULO DE MEDIDA ═══
  {
    name: 'tipoModuloMedida',
    group: 'B',
    section: 'modulo_medida',
    label: 'Tipo modulo medida',
    defaultValue: 'PANELABLE',
    inputType: 'select',
    options: ['PANELABLE', 'ENVOLVENTE', 'ARMARIO', 'INDEPENDIENTE'],
    requiredForDocs: ['MTD'],
  },
  {
    name: 'situacionModulo',
    group: 'B',
    section: 'modulo_medida',
    label: 'Situacion modulo',
    defaultValue: 'FACHADA',
    inputType: 'select',
    options: ['INTERIOR', 'FACHADA'],
    requiredForDocs: ['MTD'],
  },

  // ═══ PROTECCIONES ═══
  {
    name: 'igaNominal',
    group: 'C',
    section: 'protecciones',
    label: 'IGA corriente nominal (A)',
    calculatedBy: 'motor: P/(V x cosfi) → calibre normalizado',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'igaPoderCorte',
    group: 'C',
    section: 'protecciones',
    label: 'IGA poder de corte (kA)',
    calculatedBy: 'motor: 6kA vivienda estandar',
    requiredForDocs: ['MTD'],
  },
  {
    name: 'diferencialNominal',
    group: 'C',
    section: 'protecciones',
    label: 'Diferencial nominal (A)',
    calculatedBy: 'motor: agrupacion circuitos',
    requiredForDocs: ['MTD', 'CIE'],
  },
  {
    name: 'diferencialSensibilidad',
    group: 'C',
    section: 'protecciones',
    label: 'Diferencial sensibilidad (mA)',
    calculatedBy: 'motor: 30mA residencial',
    requiredForDocs: ['MTD'],
  },
  {
    name: 'protSobretensiones',
    group: 'B',
    section: 'protecciones',
    label: 'Proteccion sobretensiones',
    defaultValue: false,
    inputType: 'boolean',
    requiredForDocs: ['MTD', 'CIE'],
  },

  // ═══ PUESTA A TIERRA Y VERIFICACIONES ═══
  {
    name: 'tipoElectrodos',
    group: 'B',
    section: 'tierra',
    label: 'Tipo electrodos',
    defaultValue: 'PICAS',
    inputType: 'select',
    options: ['PICAS', 'PLACAS', 'MALLAS'],
    requiredForDocs: ['MTD'],
  },
  {
    name: 'seccionLineaEnlace',
    group: 'C',
    section: 'tierra',
    label: 'Seccion linea enlace (mm2)',
    calculatedBy: 'formula: = seccionCondProteccion',
    requiredForDocs: ['MTD'],
  },
  {
    name: 'seccionCondProteccion',
    group: 'C',
    section: 'tierra',
    label: 'Seccion conductor proteccion (mm2)',
    calculatedBy: 'formula: si DI<=16→PE=DI, si DI>16→16mm2',
    requiredForDocs: ['MTD'],
  },
  {
    name: 'resistenciaTierra',
    group: 'A',
    section: 'tierra',
    label: 'Resistencia tierra (ohm)',
    inputType: 'number',
    requiredForDocs: ['CIE'],
  },
  {
    name: 'resistenciaAislamiento',
    group: 'A',
    section: 'tierra',
    label: 'Resistencia aislamiento (Mohm)',
    inputType: 'number',
    requiredForDocs: ['CIE'],
  },
  {
    name: 'otrasVerificaciones',
    group: 'A',
    section: 'tierra',
    label: 'Otras verificaciones',
    inputType: 'textarea',
    optional: true,
    requiredForDocs: ['CIE'],
  },

  // ═══ EMPRESA INSTALADORA ═══
  {
    name: 'empresaNif',
    group: 'E',
    section: 'empresa',
    label: 'NIF empresa',
    autoFrom: 'tenant.empresaNif',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'empresaNombre',
    group: 'E',
    section: 'empresa',
    label: 'Nombre empresa',
    autoFrom: 'tenant.empresaNombre',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'empresaCategoria',
    group: 'E',
    section: 'empresa',
    label: 'Categoria empresa',
    autoFrom: 'tenant.empresaCategoria',
    requiredForDocs: ['CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'empresaRegNum',
    group: 'E',
    section: 'empresa',
    label: 'Num. registro industrial',
    autoFrom: 'tenant.empresaRegNum',
    requiredForDocs: ['CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'empresaTipoVia',
    group: 'E',
    section: 'empresa',
    label: 'Tipo via empresa',
    autoFrom: 'tenant.empresaTipoVia',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'empresaNombreVia',
    group: 'E',
    section: 'empresa',
    label: 'Nombre via empresa',
    autoFrom: 'tenant.empresaNombreVia',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'empresaNumero',
    group: 'E',
    section: 'empresa',
    label: 'Numero empresa',
    autoFrom: 'tenant.empresaNumero',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'empresaLocalidad',
    group: 'E',
    section: 'empresa',
    label: 'Localidad empresa',
    autoFrom: 'tenant.empresaLocalidad',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'empresaProvincia',
    group: 'E',
    section: 'empresa',
    label: 'Provincia empresa',
    autoFrom: 'tenant.empresaProvincia',
    requiredForDocs: ['CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'empresaCp',
    group: 'E',
    section: 'empresa',
    label: 'CP empresa',
    autoFrom: 'tenant.empresaCp',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'empresaTelefono',
    group: 'E',
    section: 'empresa',
    label: 'Telefono empresa',
    autoFrom: 'tenant.empresaTelefono',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'empresaMovil',
    group: 'E',
    section: 'empresa',
    label: 'Movil empresa',
    autoFrom: 'tenant.empresaMovil',
    requiredForDocs: ['SOLICITUD_BT'],
  },
  {
    name: 'empresaEmail',
    group: 'E',
    section: 'empresa',
    label: 'Email empresa',
    autoFrom: 'tenant.empresaEmail',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },

  // ═══ INSTALADOR / TECNICO ═══
  {
    name: 'instaladorNombre',
    group: 'E',
    section: 'instalador',
    label: 'Nombre instalador',
    autoFrom: 'installer.nombre',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'instaladorNif',
    group: 'E',
    section: 'instalador',
    label: 'NIF instalador',
    autoFrom: 'installer.nif',
    requiredForDocs: ['CIE'],
  },
  {
    name: 'instaladorCertNum',
    group: 'E',
    section: 'instalador',
    label: 'Num. certificado instalador',
    autoFrom: 'installer.certNum',
    requiredForDocs: ['MTD'],
  },
  {
    name: 'tipoAutor',
    group: 'B',
    section: 'instalador',
    label: 'Tipo autor',
    defaultValue: 'INSTALADOR',
    inputType: 'select',
    options: ['INSTALADOR', 'TECNICO'],
    requiredForDocs: ['MTD'],
  },
  {
    name: 'installerId',
    group: 'E',
    section: 'instalador',
    label: 'Instalador',
    autoFrom: 'installer.id',
  },
  // technicianId → grupo D (solo si tipoAutor=TECNICO, no aplica por defecto)

  // ═══ DISTRIBUIDORA (visible en datos guiados, auto-relleno desde tenant) ═══
  {
    name: 'distribuidora',
    group: 'A',
    section: 'tecnico',
    label: 'Distribuidora',
    autoFrom: 'tenant.distribuidoraHab',
    inputType: 'select',
    options: [
      '0021 - I-DE Redes Eléctricas Inteligentes',
      '0022 - UFD Distribución Electricidad',
      '0031 - E-Distribución Redes Digitales',
      '0026 - Hidrocantábrico',
      '0483 - Distribución Eléctrica del Tajuña',
      '0494 - Distribución Eléctrica El Pozo',
      '0314 - Hidroeléctrica Vega',
      '0148 - Distribución Eléctrica Las Mercedes',
      '0027 - Viesgo',
    ],
    requiredForDocs: ['CIE', 'SOLICITUD_BT'],
  },

  // ═══ PRESUPUESTO ═══
  {
    name: 'presupuestoMateriales',
    group: 'A',
    section: 'presupuesto',
    label: 'Coste materiales (EUR)',
    inputType: 'number',
    requiredForDocs: ['MTD'],
  },
  {
    name: 'presupuestoManoObra',
    group: 'A',
    section: 'presupuesto',
    label: 'Coste mano de obra (EUR)',
    inputType: 'number',
    requiredForDocs: ['MTD'],
  },
  {
    name: 'presupuestoTotal',
    group: 'C',
    section: 'presupuesto',
    label: 'Coste total (EUR)',
    calculatedBy: 'formula: materiales + mano obra',
    requiredForDocs: ['MTD'],
  },

  // ═══ CERTIFICACION ═══
  {
    name: 'aplicaReeae',
    group: 'B',
    section: 'certificacion',
    label: 'Aplica REEAE',
    defaultValue: false,
    inputType: 'boolean',
    requiredForDocs: ['CIE'],
  },
  // potLuminariasReeae → grupo D (no aplica vivienda)
  {
    name: 'aplicaItcBt51',
    group: 'B',
    section: 'certificacion',
    label: 'Aplica ITC-BT-51 (domotica)',
    defaultValue: false,
    inputType: 'boolean',
    requiredForDocs: ['CIE'],
  },

  // ═══ FIRMA ═══
  {
    name: 'firmaLugar',
    group: 'B',
    section: 'firma',
    label: 'Lugar firma',
    defaultValue: 'MADRID',
    inputType: 'text',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  {
    name: 'firmaFecha',
    group: 'C',
    section: 'firma',
    label: 'Fecha firma',
    calculatedBy: 'auto: fecha actual al generar documento',
    requiredForDocs: ['MTD', 'CIE', 'SOLICITUD_BT'],
  },
  // signerId → grupo D (firma digital, fase futura)

  // ═══ INFO ADICIONAL ═══
  {
    name: 'infoAdicional',
    group: 'A',
    section: 'info',
    label: 'Descripcion obras (CIE)',
    inputType: 'textarea',
    optional: true,
    requiredForDocs: ['CIE'],
  },
  {
    name: 'memoriaDescriptiva',
    group: 'A',
    section: 'info',
    label: 'Memoria descriptiva (MTD pag 6)',
    inputType: 'textarea',
    optional: true,
    requiredForDocs: ['MTD'],
  },
];
