/**
 * CIE Field Mapping: Installation DB fields → Excel cell (UNO row/col)
 *
 * Template: CERTIFICADO_BASICO.xls (original BIFF8)
 * Written via LibreOffice UNO: getCellByPosition(col_idx, row_idx) — both 0-indexed
 *
 * IMPORTANT: We ONLY write data cells. Formula cells are computed by the
 * spreadsheet itself:
 *   - R6 (CIE identifier) → generated by formulas in sheet "K"
 *   - R4 (COMPLETADO/INCOMPLETO) → generated by validation formulas
 *   - W7-W53 (FALTAN DATOS) → generated by validation formulas
 */

export interface CieFieldMapping {
  cell: string;
  col: string;
  row: number;
  field: string;
  type: 'db' | 'computed' | 'tenant';
  valueType: 'string' | 'number';
  transform?: string;
}

// ─── TITULAR (19 campos) ──────────────────────────────────────────────────────

export const TITULAR_FIELDS: CieFieldMapping[] = [
  { cell: 'B7',  col: 'B',  row: 6,  field: 'titularNif',         type: 'db', valueType: 'string' },
  { cell: 'H7',  col: 'H',  row: 6,  field: 'titularApellido1',   type: 'db', valueType: 'string' },
  { cell: 'P7',  col: 'P',  row: 6,  field: 'titularApellido2',   type: 'db', valueType: 'string' },
  { cell: 'D8',  col: 'D',  row: 7,  field: 'titularNombre',      type: 'db', valueType: 'string' },
  { cell: 'O8',  col: 'O',  row: 7,  field: 'titularEmail',       type: 'db', valueType: 'string' },
  { cell: 'D9',  col: 'D',  row: 8,  field: 'titularTipoVia',     type: 'db', valueType: 'string' },
  { cell: 'H9',  col: 'H',  row: 8,  field: 'titularNombreVia',   type: 'db', valueType: 'string' },
  { cell: 'U9',  col: 'U',  row: 8,  field: 'titularNumero',      type: 'db', valueType: 'string' },
  { cell: 'C10', col: 'C',  row: 9,  field: 'titularBloque',      type: 'db', valueType: 'string' },
  { cell: 'F10', col: 'F',  row: 9,  field: 'titularEscalera',    type: 'db', valueType: 'string' },
  { cell: 'H10', col: 'H',  row: 9,  field: 'titularPiso',        type: 'db', valueType: 'string' },
  { cell: 'J10', col: 'J',  row: 9,  field: 'titularPuerta',      type: 'db', valueType: 'string' },
  { cell: 'M10', col: 'M',  row: 9,  field: 'titularLocalidad',   type: 'db', valueType: 'string' },
  { cell: 'C11', col: 'C',  row: 10, field: 'titularProvincia',   type: 'db', valueType: 'string' },
  { cell: 'I11', col: 'I',  row: 10, field: 'titularCp',          type: 'db', valueType: 'string' },
  { cell: 'M11', col: 'M',  row: 10, field: 'titularTelefono',    type: 'db', valueType: 'string' },
  { cell: 'S11', col: 'S',  row: 10, field: 'titularMovil',       type: 'db', valueType: 'string' },
  { cell: 'F12', col: 'F',  row: 11, field: 'representanteNombre', type: 'db', valueType: 'string' },
  { cell: 'T12', col: 'T',  row: 11, field: 'representanteNif',   type: 'db', valueType: 'string' },
];

// ─── EMPLAZAMIENTO (10 campos) ───────────────────────────────────────────────

export const EMPLAZAMIENTO_FIELDS: CieFieldMapping[] = [
  { cell: 'C16', col: 'C',  row: 15, field: 'emplazTipoVia',     type: 'db', valueType: 'string' },
  { cell: 'G16', col: 'G',  row: 15, field: 'emplazNombreVia',   type: 'db', valueType: 'string' },
  { cell: 'S16', col: 'S',  row: 15, field: 'emplazNumero',      type: 'db', valueType: 'string' },
  { cell: 'U16', col: 'U',  row: 15, field: 'emplazCp',          type: 'db', valueType: 'string' },
  { cell: 'C17', col: 'C',  row: 16, field: 'emplazBloque',      type: 'db', valueType: 'string' },
  { cell: 'F17', col: 'F',  row: 16, field: 'emplazEscalera',    type: 'db', valueType: 'string' },
  { cell: 'H17', col: 'H',  row: 16, field: 'emplazPiso',        type: 'db', valueType: 'string' },
  { cell: 'J17', col: 'J',  row: 16, field: 'emplazPuerta',      type: 'db', valueType: 'string' },
  { cell: 'M17', col: 'M',  row: 16, field: 'emplazLocalidad',   type: 'db', valueType: 'string' },
  { cell: 'E18', col: 'E',  row: 17, field: 'contadorUbicacion', type: 'db', valueType: 'string' },
];

// ─── CARACTERÍSTICAS TÉCNICAS (21 campos) ────────────────────────────────────

export const TECNICAS_FIELDS: CieFieldMapping[] = [
  { cell: 'C20', col: 'C',  row: 19, field: 'tipoActuacion',       type: 'db',       valueType: 'string' },
  { cell: 'J20', col: 'J',  row: 19, field: 'temporalidad',        type: 'db',       valueType: 'number' },
  { cell: 'M20', col: 'M',  row: 19, field: 'cups',                type: 'db',       valueType: 'string' },
  { cell: 'U20', col: 'U',  row: 19, field: 'superficieM2',        type: 'db',       valueType: 'number' },
  { cell: 'D21', col: 'D',  row: 20, field: 'potMaxAdmisible',     type: 'db',       valueType: 'number' },
  { cell: 'J21', col: 'J',  row: 20, field: 'tipoInstalacionCie',  type: 'db',       valueType: 'string' },
  { cell: 'U21', col: 'U',  row: 20, field: 'aforo',               type: 'db',       valueType: 'string' },
  { cell: 'D22', col: 'D',  row: 21, field: 'potAmpliacion',       type: 'computed', valueType: 'string', transform: 'potAmpOrNA' },
  { cell: 'J22', col: 'J',  row: 21, field: '_tipoSuministro',     type: 'computed', valueType: 'string', transform: 'tipoSuministro' },
  { cell: 'M22', col: 'M',  row: 21, field: 'supplyVoltage',       type: 'db',       valueType: 'number' },
  { cell: 'T22', col: 'T',  row: 21, field: 'seccionDi',           type: 'db',       valueType: 'number' },
  { cell: 'D23', col: 'D',  row: 22, field: 'potOriginal',         type: 'computed', valueType: 'string', transform: 'potOrigOrNA' },
  { cell: 'T23', col: 'T',  row: 22, field: 'esquemaDistribucion', type: 'db',       valueType: 'string' },
  { cell: 'I24', col: 'I',  row: 23, field: 'puntoConexion',       type: 'db',       valueType: 'string' },
  { cell: 'M24', col: 'M',  row: 23, field: 'tipoAcometida',       type: 'db',       valueType: 'string' },
  { cell: 'P24', col: 'P',  row: 23, field: 'tipoCgp',             type: 'db',       valueType: 'string' },
  { cell: 'T24', col: 'T',  row: 23, field: 'inBaseCgp',           type: 'db',       valueType: 'string' },
  { cell: 'J25', col: 'J',  row: 24, field: 'igaNominal',          type: 'db',       valueType: 'number' },
  { cell: 'P25', col: 'P',  row: 24, field: 'protSobretensiones',  type: 'computed', valueType: 'string', transform: 'boolToSiNo' },
  { cell: 'U25', col: 'U',  row: 24, field: '_intDiferencial',     type: 'computed', valueType: 'string', transform: 'hasDiferencial' },
  { cell: 'F26', col: 'F',  row: 25, field: 'distribuidora',       type: 'db',       valueType: 'string' },
];

// ─── INFORMACIÓN ADICIONAL ───────────────────────────────────────────────────

export const INFO_FIELDS: CieFieldMapping[] = [
  { cell: 'A28', col: 'A', row: 27, field: 'infoAdicional', type: 'db', valueType: 'string' },
];

// ─── EMPRESA INSTALADORA (14 campos) ─────────────────────────────────────────

export const EMPRESA_FIELDS: CieFieldMapping[] = [
  { cell: 'B30', col: 'B', row: 29, field: 'empresaNif',       type: 'db', valueType: 'string' },
  { cell: 'H30', col: 'H', row: 29, field: 'empresaNombre',    type: 'db', valueType: 'string' },
  { cell: 'G31', col: 'G', row: 30, field: 'empresaCategoria', type: 'db', valueType: 'string' },
  { cell: 'R31', col: 'R', row: 30, field: 'empresaRegNum',    type: 'db', valueType: 'string' },
  { cell: 'E32', col: 'E', row: 31, field: 'instaladorNombre', type: 'db', valueType: 'string' },
  { cell: 'S32', col: 'S', row: 31, field: 'instaladorNif',    type: 'db', valueType: 'string' },
  { cell: 'D33', col: 'D', row: 32, field: 'empresaTipoVia',   type: 'db', valueType: 'string' },
  { cell: 'H33', col: 'H', row: 32, field: 'empresaNombreVia', type: 'db', valueType: 'string' },
  { cell: 'Q33', col: 'Q', row: 32, field: 'empresaNumero',    type: 'db', valueType: 'string' },
  { cell: 'U33', col: 'U', row: 32, field: 'empresaCp',        type: 'db', valueType: 'string' },
  { cell: 'C34', col: 'C', row: 33, field: 'empresaLocalidad', type: 'db', valueType: 'string' },
  { cell: 'I34', col: 'I', row: 33, field: 'empresaProvincia', type: 'db', valueType: 'string' },
  { cell: 'M34', col: 'M', row: 33, field: 'empresaTelefono',  type: 'db', valueType: 'string' },
  { cell: 'P34', col: 'P', row: 33, field: 'empresaMovil',     type: 'db', valueType: 'string' },
  { cell: 'R34', col: 'R', row: 33, field: 'empresaEmail',     type: 'db', valueType: 'string' },
];

// ─── CERTIFICACIÓN (5 campos) ────────────────────────────────────────────────

export const CERTIFICACION_FIELDS: CieFieldMapping[] = [
  { cell: 'L38', col: 'L', row: 37, field: 'tipoDocumentacion', type: 'db',       valueType: 'string' },
  { cell: 'A40', col: 'A', row: 39, field: 'aplicaReeae',       type: 'computed', valueType: 'string', transform: 'boolToSiNo' },
  { cell: 'T40', col: 'T', row: 39, field: 'potLuminariasReeae', type: 'db',      valueType: 'number' },
  { cell: 'A42', col: 'A', row: 41, field: 'aplicaItcBt51',     type: 'computed', valueType: 'string', transform: 'boolToSiNo' },
  { cell: 'B43', col: 'B', row: 42, field: '_fechaFirma',       type: 'computed', valueType: 'string', transform: 'formatFechaFirma' },
];

// ─── VERIFICACIONES (3 campos) ───────────────────────────────────────────────

export const VERIFICACIONES_FIELDS: CieFieldMapping[] = [
  { cell: 'S51', col: 'S', row: 50, field: 'resistenciaTierra',     type: 'db', valueType: 'number' },
  { cell: 'S52', col: 'S', row: 51, field: 'resistenciaAislamiento', type: 'db', valueType: 'number' },
  { cell: 'S53', col: 'S', row: 52, field: 'otrasVerificaciones',   type: 'db', valueType: 'string' },
];

// ─── ALL FIELDS ──────────────────────────────────────────────────────────────

export const ALL_CIE_FIELDS: CieFieldMapping[] = [
  ...TITULAR_FIELDS,
  ...EMPLAZAMIENTO_FIELDS,
  ...TECNICAS_FIELDS,
  ...INFO_FIELDS,
  ...EMPRESA_FIELDS,
  ...CERTIFICACION_FIELDS,
  ...VERIFICACIONES_FIELDS,
];

// ─── Optional fields (not required for "COMPLETADO") ─────────────────────────

export const OPTIONAL_FIELDS = new Set([
  'titularBloque', 'titularEscalera', 'titularMovil',
  'representanteNombre', 'representanteNif',
  'emplazBloque', 'emplazEscalera',
  'temporalidad', 'cups', 'aforo',
  'potAmpliacion', 'potOriginal', 'potLuminariasReeae',
  'tipoCgp', 'inBaseCgp',
  'otrasVerificaciones', 'infoAdicional', 'contadorUbicacion',
]);
